### ISSUE TITLE
Unit testing Service Fabric Queryable

### ISSUE THREAD

**Issue by PrabhujiMudragalla** [jessebenson/service-fabric-queryable#16]
Hi Team, 

We are trying to create unit test cases for Queryable Reliable Indexed Dictionary, but we are facing below error message:

**_InnerException	{System.InvalidProgramException: No query over the data source was specified.
   at ServiceFabric.Extensions.Services.Queryable.LINQ.ReliableIndexedDictionaryQueryContext.Execute[TKey,TValue](Expression expression, IReliableStateManager stateManager, IReliableIndexedDictionary`2 dictionary, Boolean IsEnumerable)}	System.Exception {System.InvalidProgramException}**

This issues is observed only on unit tests, which are querying on indexed columns. We are able to run application and query all endpoints but such unit test cases are failing.

Can you please help us out on this issue?

**Comment by jessebenson** [comment]
Have you taken a look at (and ran) the unit tests that query against a queryable reliable indexed dictionary here:
https://github.com/jessebenson/service-fabric-queryable/blob/master/src/ServiceFabric.Extensions.Services.Queryable.Test/LINQTests.cs

**Comment by PrabhujiMudragalla** [comment]
We tried to implement same mocking mechanism in our Stateful services, we observed following behaviour:
**Error: One or more errors occurred. (Object reference not set to an instance of an object.)**
When we tried to add where class to QueryableReliableIndexedDictionary test cases are failing but endpoints are working fine, but only select in query is working fine in endpoints and test case. 
**Stacktrace:**
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at ServiceFabric.Extensions.Services.Queryable.LINQ.ReliableIndexedDictionaryProvider`2.Execute[TResult](Expression expression)
   at ServiceFabric.Extensions.Services.Queryable.LINQ.QueryableReliableIndexedDictionary`3.GetEnumerator()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Linq.SystemCore_EnumerableDebugView`1.get_Items()

**Comment by PrabhujiMudragalla** [comment]
Hi Jesse, 

Issues is observed due to IReliableStateManager, we are mocking this object in our application but that is not same as you did, so we observed this issue. We updated our Mocking logic with respect to the ServiceFabric.Data.Mocks and this issue is resolved. 
[]([https://github.com/jessebenson/service-fabric-queryable/tree/master/src/ServiceFabric.Data.Mocks](https://github.com/jessebenson/service-fabric-queryable/tree/master/src/ServiceFabric.Data.Mocks))
Thanks for your support.
